### PR TITLE
feat(watch): add trigger for file/directory watching

### LINKED ISSUE #426: File watch / change trigger
Do we want to implement a file watch trigger?

Use case: @boc-tothefuture's sitemap template system - regenerate the sitemap automatically

For me, I have been playing with DeepStack and I have a directory structure to store people's photos for face recognition. I want to automatically register any new photos on DeepStack

### PR DESCRIPTION
**Pull request by boc-tothefuture**
Closes #426

### CODE REVIEW

**Comment by jimtng** [comment]
This looks more comprehensive than what I expected. It's great!

Where's __conf__ coming from?

Did you know it's available inside ENV?

**Comment by boc-tothefuture** [comment]
> This looks more comprehensive than what I expected. It's great!
> 
> Where's `__conf__` coming from?
> 
> Did you know it's available inside ENV?

We would have to expose __conf__ 

I didn't know it was in ENV, I was going to grab it from the OpenHAB class where we get it in the binding.

**Review by jimtng — COMMENTED** [review]
Great work!

**Comment by jimtng** [comment]
The docs hasn't been updated yet https://boc-tothefuture.github.io/openhab-jruby/usage/triggers/

**Pull request merged**
