### PR TITLE
feat: add rule description

### PR DESCRIPTION
**Pull request by jimtng**
Add description feature, resolve https://github.com/boc-tothefuture/openhab-jruby/issues/32

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Can you add a new cucumber test in a new file called features/description.feature ?

I can help you if you haven't ever done that before. But for all new features it is critical we have formal tests to catch any regressions and make sure changes don't break anything.

It is fairly easy to do.

**Comment by jimtng** [comment]
> Can you add a new cucumber test in a new file called features/description.feature ?
I'll give it a go. This is ALL very new to me.

**Comment by jimtng** [comment]
I've added description.feature - how does it look?

**Comment by boc-tothefuture** [comment]
Each of those steps listed in the scenarios ends up being executed as code.  So this step
`
Then The rule 'Test rule' should have 'This is the rule description' as its description in OpenHAB GUI
`
Will fail.  I also am not sure we want to scrape the GUI.  Is it available via a rest call about the rules instead? 

Do you have a ruby development environment setup? 

If from the main repo you run:
`rake openhab:setup`
It should setup your test instance of OpenHAB for the cucumber tests.
It will actually fail the first time you run it, so you will need to do this:
`rake openhab:setup`
then in another window start the version of openhab it just downloaded by going into  the tmp/openhab directory and running `./start.sh` (I am assuming you are on linux or a mac??)
then running
`rake openhab:setup` again.

Once that is done you can run:
`cucumber features/description.feature` to execute your tests.

This is critical to ensuring that changes we make get tested and don't have regressions (i.e. we change something we think is unrelated and then this breaks).  

Also, I know this setup process isn't clean (with it not running the full way through every time) and it is on my list to fix. 

I am happy to help guide here and we should use this exercise as a way of documenting the development process.

**Comment by boc-tothefuture** [comment]
Also, I know it may seem daunting at first and a lot of extra work for your small change..  But once you have it setup you can make changes, test locally, and be fairly confident they are going to work and not break other things!

**Comment by jimtng** [comment]
OK.... this is going to take me a while... :) 
```
$ rake openhab:setup --trace
rake aborted!
LoadError: cannot load such file -- rubocop/rake_task
```

I'll try to figure it out.

**Comment by boc-tothefuture** [comment]
I am happy to help. 

So if ruby is installed.

run this:
`bundle`
This should install all the dependencies for the project (they are specified in Gemfile). 

Then you should be able to either run
rake openhab:setup
OR
bundle exec rake openhab:setup

Depending on your ruby environment.

**Comment by jimtng** [comment]
I'm on a mac laptop, but my openhab is on linux. It sounds like this will install openhab on my mac if I run it locally. That's fine. However I'm still struggling with installing gem requiring sudo, etc, so I am going to install rbenv first. I am very fresh/total newbie when it comes to Ruby. I wish I had looked into it 20 years ago!

**Comment by boc-tothefuture** [comment]
Yep, you will want rbenv installed and it shouldn't require sudo once you do that. 

You will want rbenv to install version 2.5.8 of ruby which matches what we have in JRuby. 

There is a .ruby-version file in the directory which should make rbenv choose the right version (if you have multiple installed).

Would you mind documenting this as you go?  I got there through a winding exploratory path so didn't document it.

**Comment by jimtng** [comment]
I'm now at the rake openhab:setup stage. 

```
wget https://openhab.jfrog.io/openhab/libs-milestone-local/org/openhab/distro/openhab/3.0.0.RC2/openhab-3.0.0.RC2.zip
rake aborted!
Command failed with status (127): [wget https://openhab.jfrog.io/openhab/libs...]
```
It seems that the file isn't there.

**Comment by jimtng** [comment]
OK Finally there. I got this error:

```
$ cucumber features/description.feature
Using the default profile...
Feature: Rule languages supports description feature

  Background:                                      # features/description.feature:3
    Given Clean OpenHAB with latest Ruby Libraries # features/step_definitions/openhab.rb:6
      no implicit conversion of String into Integer (TypeError)
      ./features/support/openhab.rb:57:in `block in delete_rules'
      ./features/support/openhab.rb:56:in `delete_rules'
      ./features/step_definitions/openhab.rb:9:in `"Clean OpenHAB with latest Ruby Libraries"'
      features/description.feature:4:in `Clean OpenHAB with latest Ruby Libraries'

  Scenario: Set the rule description                                                                       # features/description.feature:6
    Given a rule:                                                                                          # features/description.feature:7
      """
      rule 'Test rule' do
      description 'This is the rule description'
      on_start
      end
      """
    When I deploy the rule                                                                                 # features/step_definitions/openhab_rules.rb:42
    Then The rule 'Test rule' should have 'This is the rule description' as its description in OpenHAB GUI # features/description.feature:15

Failing Scenarios:
cucumber features/description.feature:6 # Scenario: Set the rule description

1 scenario (1 failed)
4 steps (1 failed, 1 skipped, 2 undefined)
0m1.770s

You can implement step definitions for undefined steps with these snippets:

Given('a rule:') do |doc_string|
  pending # Write code here that turns the phrase above into concrete actions
end

Then('The rule {string} should have {string} as its description in OpenHAB GUI') do |string, string2|
  pending # Write code here that turns the phrase above into concrete actions
end
```

**Comment by boc-tothefuture** [comment]
I pushed a change (just now) which I had locally but not pushed that relaxes the syntax for the "given a rule:" step.  So if you pull main branch down and merge it into your branch your first error should go away.

For the second step, I think we want to change that to be:

```
Then The rule 'Test rule' should have 'This is the rule description' as its description
```

Once you do that, we need to write the code in features/step_definitions file.  If you make that change and push it up I can write that code and push it back up so you can look at it.  It's not complicated, but might be easier for you to just look at the code I write rather than explain how to write it?

**Comment by boc-tothefuture** [comment]
Take a look at what I did and let me know if it makes sense?

**Comment by boc-tothefuture** [comment]
Also, pull it down and make sure it tests correctly for you :-)

**Comment by jimtng** [comment]
Still seeing this error:
```
$ cucumber features/description.feature
Using the default profile...
Feature: Rule languages supports description feature

  Background:                                      # features/description.feature:3
    Given Clean OpenHAB with latest Ruby Libraries # features/step_definitions/openhab.rb:6
      no implicit conversion of String into Integer (TypeError)
      ./features/support/openhab.rb:57:in `block in delete_rules'
      ./features/support/openhab.rb:56:in `delete_rules'
      ./features/step_definitions/openhab.rb:9:in `"Clean OpenHAB with latest Ruby Libraries"'
      features/description.feature:4:in `Clean OpenHAB with latest Ruby Libraries'

  Scenario: Set the rule description                                                        # features/description.feature:6
    Given a rule:                                                                           # features/step_definitions/openhab_rules.rb:29
      """
      rule 'Test rule' do
        description 'This is the rule description'
        on_start
        run {}
      end
      """
    When I deploy the rule                                                                  # features/step_definitions/openhab_rules.rb:42
    Then The rule 'Test rule' should have 'This is the rule description' as its description # features/step_definitions/openhab.rb:99

Failing Scenarios:
cucumber features/description.feature:6 # Scenario: Set the rule description

1 scenario (1 failed)
4 steps (1 failed, 3 skipped)
0m1.669s
```

**Comment by boc-tothefuture** [comment]
Is openhab running locally from the tmp/openhab directory?

**Comment by jimtng** [comment]
For the record, these were the commands I typed on my mac to get the rake / cucumber running, starting from installing ruby with rbenv, wget, etc.

assuming current working directory is openhab-jruby
```
brew install rbenv
rbenv init
eval "$(rbenv init -)"
rbenv install 2.5.8
rbenv local 2.5.8
eval "$(rbenv init -)"
rbenv version #verify 
ruby -v
gem install bundler
bundle
brew install wget
rake openhab:setup
cd tmp/openhab
./start.sh
cd ../..
rake openhab:setup
cucumber features/description.feature
```

**Comment by jimtng** [comment]
> Is openhab running locally from the tmp/openhab directory?

yes, it's still running in another terminal window

**Comment by boc-tothefuture** [comment]
It is getting back something unexpected when it requests the rules.

Between lines 55 and 56 of can you add the following line:
```
puts Rest.rules
```
I would be curious to see what is coming back for you.

**Comment by jimtng** [comment]
I stopped openhab and started it again. It passed now. 

Thanks for your help.

**Comment by boc-tothefuture** [comment]
No problem.. did the test code make sense?

**Comment by boc-tothefuture** [comment]
One last request, can you update the changelog and bump the version in version.rb to 2.3.0?

**Comment by jimtng** [comment]
> No problem.. did the test code make sense?

Yes it does.

I've updated the version.rb and changelog. Wow a lot of stuff to do just for one little thing :)

**Pull request merged**
