### PR TITLE
Build: Introduce CI/CD Builds

### PR DESCRIPTION
**Pull request by boc-tothefuture**

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
@jimtng Can you take a look at this?
This is a lot going on here, but I think I now have a stable, quick (10min) or so CI/CD build. I reverted a couple of changes you made so I wanted to make sure you could look at them.

1. I put the Gemfile.lock back in.  Some research shows that file should be in source control so the developers, build, and CI systems are all using the same gems.
2. I had to revert the change where the rule deployed step was on rule start. A lot of the step timing assumes that the rule has been processed and is ready to receive commands/triggers. I added a different step if you want to move on before rule is processed.

**Comment by jimtng** [comment]
I checked out the 'build' branch and tried running "cucumber features/states.feature" and got this:

```
$ cucumber features/states.feature 
cannot load such file -- tty-command (LoadError)
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/jimmy/Projects/openhab-jruby/features/support/openhab.rb:5:in `<top (required)>'
/Users/jimmy/Projects/openhab-jruby/features/support/env.rb:3:in `require_relative'
/Users/jimmy/Projects/openhab-jruby/features/support/env.rb:3:in `<top (required)>'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/glue/registry_and_more.rb:121:in `load_code_file'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/runtime/support_code.rb:81:in `block in load_files!'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/runtime/support_code.rb:80:in `each'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/runtime/support_code.rb:80:in `load_files!'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/runtime.rb:255:in `load_step_definitions'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/runtime.rb:72:in `run!'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/lib/cucumber/cli/main.rb:29:in `execute!'
/Users/jimmy/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/cucumber-5.2.0/bin/cucumber:9:in `<top (required)>'
/Users/jimmy/.rbenv/versions/2.5.8/bin/cucumber:23:in `load'
/Users/jimmy/.rbenv/versions/2.5.8/bin/cucumber:23:in `<main>'
```

Perhaps we need 'setup instructions' to set up the development environment, for n00bs like me.

Anyhow I ran `bundle install`, and re-ran cucumber and now it just stopped like this:

```
$ cucumber features/states.feature 
Using the default profile...
Feature: Rule languages supports storing and restoring states

  Background:                                      # features/states.feature:3
```

Then I pressed ^C:
```
^C
Exiting... Interrupt again to exit immediately.
    Given Clean OpenHAB with latest Ruby Libraries # features/step_definitions/openhab.rb:6
      exit (SystemExit)
      ./features/step_definitions/openhab.rb:7:in `system'
      ./features/step_definitions/openhab.rb:7:in `"Clean OpenHAB with latest Ruby Libraries"'
      features/states.feature:4:in `Clean OpenHAB with latest Ruby Libraries'
    And items:                                     # features/step_definitions/openhab.rb:59
      | type   | name    | label             | state |
      | Switch | Switch1 | Switch Number One | OFF   |
      | Switch | Switch2 | Switch Number Two | OFF   |

  Scenario: States can be stored and restored using store_states # features/states.feature:11
    Given code in a rules file:                                  # features/step_definitions/openhab_rules.rb:81
      """
      states = store_states Switch1, Switch2
      Switch1 << ON
      after(5.seconds) { states.restore }
      """
    When I deploy the rule                                       # features/step_definitions/openhab_rules.rb:69
    Then "Switch1" should be in state "ON" within 2 seconds      # features/step_definitions/openhab.rb:134
    But If I wait 5 seconds                                      # features/step_definitions/support.rb:5
    Then "Switch1" should be in state "OFF" within 2 seconds     # features/step_definitions/openhab.rb:134
      No such file or directory @ rb_sysopen - tmp/cucumber_logs/states.feature_11 (Errno::ENOENT)
      ./features/support/gather_logs.rb:8:in `After'

Failing Scenarios:
cucumber features/states.feature:11 # Scenario: States can be stored and restored using store_states

1 scenario (1 failed)
7 steps (1 failed, 6 skipped)
1m17.217s
```

**Comment by boc-tothefuture** [comment]
Hmm.
Can you try this to reset everything.
`bundle.exec rake clean openhab:clobber openhab:setup`
`bundle exec cucumber features/states.feature`

**Comment by jimtng** [comment]
> Hmm.
> Can you try this to reset everything.
> `bundle exec rake clean openhab:clobber openhab:setup`
> `bundle exec cucumber features/states.feature`

Yes! That did the trick, thanks!

**Pull request merged**
