### PR TITLE
refactor: consistent module namespacing

### PR DESCRIPTION
**Pull request by boc-tothefuture**

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Addresses #3

**Comment by boc-tothefuture** [comment]
This PR attempts to bring some sanity to the module/project layout that grew organically and incorrectly.
Changes:
1. Everything (besides monkeypatching the core ruby library) is in a module instead of some random elements being top level
2. File structure matches module restructure

Top level modules / directories are as follows:
- Core  (Anything for dealing w/ the OpenHAB core (entity lookup, osgi, etc)
- DSL (Anything that presents in the end user DSL )
- Log (Anything related to logging)
-

**Comment by boc-tothefuture** [comment]
@jimtng and @pacive can you review before I merge?

**Review by pacive — APPROVED** [review]
Can't see any obvious issues, mostly files moved around and namespaces updated accordingly, right? Will rebase my prs and update them accordingly after you merge this.

**Comment by boc-tothefuture** [comment]
ok, I will let @jimtng weigh in before merging.

**Comment by jimtng** [comment]
Thanks for checking. Please go ahead. I'll rebase as needed.

**Pull request merged**
