### PR TITLE
feat(color): support for color items and hsb type

### LINKED ISSUE #34: Add Color Item Type

### PR DESCRIPTION
**Pull request by ccutrer**
closes #34

this still needs docs written

### CODE REVIEW

**Comment by ccutrer** [comment]
oh yeah, you're right, I didn't get to them. it's been a crazy week! I've had a good vacation though ;)

I don't care if we get them into this PR, or add them separately. I guess I have a slight preference to get this in sooner, as I'm already depending on it in my rules, so the sooner it's in the sooner I can get back to a regular release :).

**Comment by boc-tothefuture** [comment]
Are you planning to add the docs to this PR?  I am fine w/ merging this and then I can open a PR for the hash support.

**Comment by ccutrer** [comment]
> @ccutrer - Couple questions on the usage notes:
> 
> ```
> HueBulb << "#ff0000" # send 'red' as a command
> HueBulb.red # => 100%
> HueBulb.hue # => 0 °
> HueBulb.brightness # => 100%
> HueBulb.to_rgb # => [100%, 0%, 0%]
> HueBulb.rgb.to_s(16) # => "0xff0000"
> HueBulb.on? # => true
> ```
> 
>  1. When things are returning a % what type is that?
> 2. This my ignorance, I am sure, but Hue comes back as a degree?  What type is that?
> 3. We have `to_rgb' that returns an array of percents / we were going to accept a hash - shouldn't that be consistent?
> 4. We have `to_rgb' but to get the hex color code back out we do `.rgb.to_s(16)'.  Should that be `to_rgb.to_s(16)` or should the `to_rgb` instead be `rgb`?
> 5. Should we have a `to_hex` also?

1. It's a PercentType.
2. It's a QuantityType with unit DEGREE_ANGLE. HSB is modeled as a cylinder, with hue (the color wheel) being an angle, saturation (how much color) a percentage, and brightness a percentage.
3/4. 🤷  I was just documenting the java methods (https://www.openhab.org/javadoc/latest/org/openhab/core/library/types/hsbtype). `toRGB` returns an array with PercentType components, and `getRGB` returns an int (it actually always has the top 8 bits set to 0xff for 100% opacity, which seemed less than useful which is why I renamed it to `argb` and masked those out for `rib`).
5. Oh yeah, I totally added that method, need to document it.

**Comment by ccutrer** [comment]
docs tweaked. let me know if you think we should do some method renames though.

**Pull request merged**
