### PR TITLE
perf(timeofdayrangeelement): subclass Numeric to make comparisons more efficient

### LINKED ISSUE #145: TimeOfDay Range makes A LOT of comparison operations
When trying to make DateTimeItems work with TimeOfDay Ranges I noticed that it seems as the range comparison checks against every single second-of-day within the range, which seems really unnecessary. The only comparisons that needs to be made is to the first and last element (which is how other ranges in ruby work I believe?) Haven't looked at the code enough to see where this happens, but will have a look.
Cucumber test:
```
  Scenario Outline: Between ranges can be used in case statements
    Given a rule template:
      """
      case <compare>
      when between(<between>)
        logger.info("Within time range")
      else
        logger.info("Not in time range")
      end
      """
    When I deploy the rule
    Then It <should> log "Within time range" within 5 seconds
    Examples: Checks Time, TimeOfDay and Strings
      | between                                                                                           | compare                                | should     |
      | '<%=(Time.now - (5*60)).strftime('%H:%M:%S')%>'..'<%=(Time.now + (5*60)).strftime('%H:%M:%S')%>'  | Time.now                               | should     |
      | '<%=(Time.now + (5*60)).strftime('%H:%M:%S')%>'..'<%=(Time.now + (10*60)).strftime('%H:%M:%S')%>' | Time.now                               | should not |
      | '<%=(Time.now - (5*60)).strftime('%H:%M:%S')%>'..'<%=(Time.now + (5*60)).strftime('%H:%M:%S')%>'  | TimeOfDay.now                          | should     |
      | '<%=(Time.now + (5*60)).strftime('%H:%M:%S')%>'..'<%=(Time.now + (10*60)).strftime('%H:%M:%S')%>' | TimeOfDay.now                          | should not |
      | '<%=(Time.now - (5*60)).strftime('%H:%M:%S')%>'..'<%=(Time.now + (5*60)).strftime('%H:%M:%S')%>'  | '<%=(Time.now).strftime('%H:%M:%S')%>' | should     |
      | '<%=(Time.now + (5*60)).strftime('%H:%M:%S')%>'..'<%=(Time.now + (10*60)).strftime('%H:%M:%S')%>' | '<%=(Time.now).strftime('%H:%M:%S')%>' | should not |
```
Log output (excerpt):
```
2021-02-09 08:50:26.963 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32367) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.964 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32368) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.965 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32368) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.966 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32369) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.967 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32369) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.968 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32370) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.969 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32370) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.970 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32371) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.971 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32371) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.972 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32372) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.974 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32372) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.975 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32373) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.976 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32373) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.977 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32374) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.978 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32374) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.978 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32375) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.979 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32375) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.980 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32376) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.981 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32376) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.982 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32377) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.983 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32377) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.984 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32378) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.985 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32378) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.986 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32379) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.987 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32379) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.988 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32380) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.989 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32380) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.990 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32381) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.991 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32381) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.992 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32382) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.993 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32382) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.994 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32383) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.995 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32383) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.996 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32384) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.997 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32384) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:26.998 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32385) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:26.999 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32385) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.000 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32386) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.001 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32386) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.002 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32387) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.003 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32387) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.004 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32388) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.006 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32388) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.007 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32389) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.009 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32389) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.010 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32390) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.011 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32390) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.012 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32391) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.013 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32391) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.014 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32392) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.015 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32392) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.016 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32393) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.017 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32393) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.018 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32394) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.020 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32394) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.021 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32395) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.022 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32395) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.023 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32396) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.025 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32396) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.026 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32397) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.028 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32397) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.029 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32398) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.030 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32398) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.031 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32399) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.032 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32399) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.034 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32400) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.035 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32400) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.036 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32401) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.037 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32401) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.038 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32402) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.039 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32402) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.040 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32403) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.042 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32403) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.043 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32404) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.045 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32404) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.047 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32405) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.049 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32405) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.050 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32406) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.051 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32406) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.052 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32407) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.053 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32407) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.054 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32408) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.056 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32408) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.057 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32409) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.058 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32409) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.059 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32410) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.061 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32410) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.062 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32411) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.064 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32411) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.065 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32412) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.066 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32412) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.067 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32413) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.069 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32413) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.070 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32414) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.072 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32414) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.073 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32415) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.074 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32415) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.075 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32416) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.077 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32416) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.079 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32417) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.080 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32417) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.081 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32418) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.082 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32418) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.083 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32419) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.084 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32419) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.085 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32420) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.086 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32420) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.087 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32421) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.088 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32421) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.089 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32422) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (-1)
2021-02-09 08:50:27.090 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32422) other SOD(118223) Other Class (String) Result (-1)
2021-02-09 08:50:27.091 [TRACE] [ore::DSL::Tod::TimeOfDayRangeElement] - SOD(32423) other SOD(32423) Other Class (OpenHAB::Core::DSL::Tod::TimeOfDayRangeElement) Result (0)
```
It also has to convert the other object to a TimeOfDayRangeElement for every single comparison, which requires a lot of extra cpu time.

### PR DESCRIPTION
**Pull request by pacive**
Fixes #145 

Signed-off-by: Anders Alfredsson <andersb86@gmail.com>

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Hey!  Thanks for the PR.  Sorry I didn't see this earlier.  I think if we just have TimeOfDayRangeElement extend numeric it will use cover? Instead of include?  

That might be better than having to maintain our own fork of range.

**Comment by pacive** [comment]
> I think if we just have TimeOfDayRangeElement extend numeric it will use cover? Instead of include?

That could be true, will try that and see how it works out.

**Comment by pacive** [comment]
That worked equally well. Rolled back and pushed a new commit.

**Comment by boc-tothefuture** [comment]
Awesome.. one minor thing, can you change the commit message to be:
perf(TimeOfDayRangeElement): subclass Numeric to make comparisons more efficient

You can see all the types [here](https://gist.github.com/brianclements/841ea7bffdb01346392c) Thanks for the PR!

**Pull request merged**
