### PR TITLE
Ci 3.2.m3

### PR DESCRIPTION
**Pull request by boc-tothefuture**

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
@ccutrer and @jimtng Can you verify you also see this behavior? https://github.com/openhab/openhab-core/issues/2562

**Comment by jimtng** [comment]
> @ccutrer and @jimtng Can you verify you also see this behavior? [openhab/openhab-core#2562](https://github.com/openhab/openhab-core/issues/2562)

Yes this happens on my production system 3.2m3 and also 3.2m4.

**Comment by jimtng** [comment]
maybe change this to m4 now that it has just been released

**Comment by boc-tothefuture** [comment]
I am going to close this @jimtng do you want to put in a PR against M4?  I still think it will break until https://github.com/openhab/openhab-core/issues/2562 is fixed.

**Comment by jimtng** [comment]
Yes, I'll do a PR for M4 and we'll wait until that slowness issue is fixed.

**Pull request closed without merging**
