### PR TITLE
feat(build): test against jruby 9.3

### PR DESCRIPTION
**Pull request by boc-tothefuture**

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
closes #277

**Comment by boc-tothefuture** [comment]
@jimtng It looks like something in the metadata section isn't compatible with JRuby 9.3 (Ruby 2.6).  Can you take a look? There are no exceptions or errors anywhere but the tests are failing.  
List of changes are here:  https://nithinbekal.com/posts/ruby-2-6/

**Comment by jimtng** [comment]
I've been working on the binding to fix #334 and in the process trying out jruby 9.3.1.0 - it throws a lot of exceptions and in general not working at all (not our library, just the binding / jruby). So in the mean time I'm using 9.2.20.0

**Comment by boc-tothefuture** [comment]
@jimtng I tried to swap in 9.3.1.0 into a running system and it didn't work (no idea why)..  But it does seem to work (as you can see from this PR) as long as you do a rake openhab:clobber.  The only thing that doesn't seem to work is the metadata.

But yeah, I did a bundle upgrade at one point and I have no idea what happened but everything seemed to break.

**Comment by boc-tothefuture** [comment]
Just FYI - I am preparing the binding to submit a PR into the add-ons.. I plan to submit this weekend.

**Comment by jimtng** [comment]
> I tried to swap in 9.3.1.0 into a running system

How did you do that?


> Just FYI - I am preparing the binding to submit a PR into the add-ons.. I plan to submit this weekend.

Once it's submitted, future PRs for the binding will go towards openhab/openhab-addons repo?

I hope #334 can be solved before that.

**Comment by jimtng** [comment]
> The only thing that doesn't seem to work is the metadata.

I added a PR to fix it.

**Comment by jimtng** [comment]
I'm using jruby 9.3.1.0 through my bundle in https://github.com/boc-tothefuture/openhab2-addons/pull/2
Other than the gem installer not working against script reload, everything else seems to be working fine. There seem to be several nice features introduced in ruby 2.6 like #then amongst others.

**Pull request merged**
