### PR TITLE
fix: set the rule name as the logger name

### LINKED ISSUE #84: logger doesn't show the rule name
Currently when logging from inside a rule, the log shows:

```ruby
rule 'rule1 ' do
  on_start
  run do
    logger.info("Test logging from rule #{name}")
  end
end
```

```
15:12:34.417 [INFO ] [.OpenHAB::Core::DSL::Rule::RuleConfig] - Test logging from rule rule1
```

What it should say is:
```
15:12:34.417 [INFO ] [jsr223.jruby.rule1] - Test logging from rule rule1
```

### PR DESCRIPTION
**Pull request by jimtng**
Fix #84 

Perhaps this fix is a bit crude, but it seems to work. @boc-tothefuture WDYT?

PS The version number is set so the other PR should be merged first.

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
You are right this does seem a bit hacky..  We probably need a way to associate an object with a name in the logger method so that during rule construction we set the name.

**Comment by jimtng** [comment]
Could we merge this now and fix it later with a more elegant solution?

**Comment by boc-tothefuture** [comment]
Let me know if #126 captures this?

**Comment by jimtng** [comment]
> Let me know if #126 captures this?

Yes, it's a better solution

**Pull request closed without merging**
