### PR TITLE
fix: items['nonexistent'] now returns nil, add items.include?

### LINKED ISSUE #101: Checking the existence of an item
Is there a more elegant way to check if an item exists, given a name?

Currently, items['ANonExistentItem'] will cause an exception. I'd have to rescue the exception to proceed.

It would be good I think if items['ANonExistentItem'] will simply return nil.

### PR DESCRIPTION
**Pull request by jimtng**
Resolve #101 
Add items.include? to check for items existence
Make items['nonexistent'] to return nil. This will enable such shortcut:

```ruby
basename = 'LivingRoom'
power_item = items["#{basename}_Light_Dimmer"] ||  items["#{basename}_Light_Power"] ||  items["#{basename}_Light_Switch"]
power_item&.on
```

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Do we want to generate and catch the stack trace or should we just use the include? method you wrote?

```
return nil unless include?(item)
```

**Comment by jimtng** [comment]
> Do we want to generate and catch the stack trace or should we just use the include? method you wrote?
> 
> ```
> return nil unless include?(item)
> ```

Calling `return nil unless include?` will involve two function calls each and every time items[] is called, whereas catching the exception only involves one call when the item exists. It only involves the exception / rescue when it doesn't exist, so to me it's more efficient for the normal case when people are referring to existing items.

**Comment by boc-tothefuture** [comment]
This really should be two commits since we shouldn't combine a fix with a feature in the same commit.  Otherwise we will get the wrong versioning from semver/conventional commits.  
Would you mind rebasing, create two commits and then force pushing with lease?

**Comment by jimtng** [comment]
Shall I keep them in one PR?

**Comment by boc-tothefuture** [comment]
One PR is fine.

**Comment by jimtng** [comment]
I've split them into two commits

**Comment by boc-tothefuture** [comment]
commit-lint is failing https://github.com/boc-tothefuture/openhab-jruby/pull/107/checks?check_run_id=1810741397

I find this super annoying but the commit messages (the part after the colon) cannot start with uppercase.  Not sure why, but that is the standard and all the tooling works off of it being formatted in a specific way.

**Comment by jimtng** [comment]
Re-submitted with lower case

**Pull request merged**
