### PR TITLE
Install JRuby Helper Library as a Ruby Gem

### PR DESCRIPTION
**Pull request by boc-tothefuture**

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
This addresses #55 

@jimtng - Could you look at this and test it out?

**Comment by jimtng** [comment]
Trying out the gem version now. Question, how can I overwrite / customise / experiment with the library when it's installed as a gem? Can I just change the files inside the gem directory?

**Comment by boc-tothefuture** [comment]
> Trying out the gem version now. Question, how can I overwrite / customise / experiment with the library when it's installed as a gem? Can I just change the files inside the gem directory?

That should work.  You can also do a 'rake build' and then do what 'rake openhab:deploy' does which is sets your GEM_HOME to point to the same gem_home dir and then run gem install ./pkg/<gem-version>.  That will update the gem.

**Comment by jimtng** [comment]
It seems to work. I've just installed it. It needed the newer version of the openhab addon jar.

**Comment by boc-tothefuture** [comment]
Yeah, it requires the new jar.. docs should be pointing it.

**Comment by jimtng** [comment]
How do people update their gem? It would be good to document that for Ruby noobs like me.

**Comment by boc-tothefuture** [comment]
> How do people update their gem - without restarting openhab? It would be good to document that for Ruby noobs like me.

You probably really shouldn't.  At least we shouldn't expose it to those not doing development.  Because of how OpenHAB works these rules are preprocessed and then stored by the OpenHAB rules engine.  So if you don't restart, some rules are going to be processed by one version of the library and updated rules by the new version. 

For development, I think in another message I explained you can just do a gem install.   but same rules would apply to a running system.

**Pull request merged**
