### PR TITLE
ci: test against 3.2 Milestone 1

### PR DESCRIPTION
**Pull request by jimtng**
Waiting on https://github.com/openhab/openhab-distro/issues/1334

### CODE REVIEW

**Comment by jimtng** [comment]
Since the change to Karaf was merged into 3.2M2, how about we add tests for 3.2M1 for now and do another PR if and when https://github.com/openhab/openhab-distro/issues/1334 is fixed?

**Comment by jimtng** [comment]
I re-ran the checks twice, for a total of 3 runs, and they passed three times. Hopefully it's safe to say that the karaf delay issue started on 3.2M2. 

Should we merge this now (with 3.2M1)?

**Comment by boc-tothefuture** [comment]
Looks like it needs to be rebased?

**Comment by jimtng** [comment]
rebased

**Pull request merged**
