### PR TITLE
fix(dependency): Update mimemagic dependency

### PR DESCRIPTION
**Pull request by boc-tothefuture**

### CODE REVIEW

**Comment by jimtng** [comment]
We should follow Rails and change mimemagic to [marcel](https://github.com/rails/marcel). Therefore I propose updating this PR and use marcel

**Comment by boc-tothefuture** [comment]
Happy to move to that.  I was just trying to get the build to work with the new version (which it should) while we evaluate options.

**Comment by jimtng** [comment]
I've been trying to solve a different mystery the past few days, and just came across `marcel` a few minutes before you posted this PR. It seems to be quite a straight forward replacement, so we might as well change over right away.

**Comment by boc-tothefuture** [comment]
@jimtng and @pacive please review.

**Review by pacive — APPROVED** [review]
Great! Are there any steps required to update when the new version is released? (I assume it does everything automatically?)

**Comment by boc-tothefuture** [comment]
It should be a non-breaking change?  It is using a different database for mime types so there might be some differences, but I doubt it would impact our users.

**Review by jimtng — APPROVED** [review]
Thank you @boc-tothefuture 
LGTM

**Pull request merged**
