### PR TITLE
feat: between creates time of day ranges

### PR DESCRIPTION
**Pull request by boc-tothefuture**

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
@jimtng Would you be willing to look at something for me?  
I cannot figure out why `cucumber features/between.feature:18` fails
but `cucumber features/between.feature:16` passes

The logic should be close to identical.  It may be something very obvious but it is escaping me.

**Comment by boc-tothefuture** [comment]
I have a couple of puts statements to help debug.. 

For the working one, I see this:
```
Between called with 07:22:21..07:32:21
Creating range from 26541..27141
My SOD: 26541 other: 27141
Results -1
My SOD: 26541 other: 26847
Results -1
My SOD: 27141 other: 26847
Results 1
```
Ruby compares the beginning to the end.
Ruby compares the beginning to the object under test
Ruby compares the end to the object under test

```
Between called with 07:22:41..07:32:41
Creating range from 26561..27161
My SOD: 26561 other: 27161
Results -1
TOD: 07:27:47 SOD: 26867
My SOD: 26561 other: 26867
Results -1
```
In the failing one.
Ruby compares the beginning to end
Ruby compare the object under test to the beginning 

then it just stops?

**Comment by jimtng** [comment]
I keep seeing 
```
00:01:26.207 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:openhab-jruby/tmp/openhab/conf/automation/jsr223/ruby/personal/cucumber_test_9adef880-d608-40f2-b8b4-415747f563cc.rb': org.jruby.embed.EvalFailedException: (NameError) uninitialized constant OpenHAB::Core::DSL::Tod::NUM_SECONDS_IN_DAY
```

**Comment by boc-tothefuture** [comment]
I don't get that error.. but I figured it out.

**Comment by boc-tothefuture** [comment]
@jimtng can you tell me if you are still having issues?

**Comment by jimtng** [comment]
There were some merges to be done (time_of_day.rb and dsl.rb), but other than that, all the tests passed now.

**Comment by boc-tothefuture** [comment]
This addressed #41

**Review by jimtng — CHANGES_REQUESTED** [review]
```
[TimeOfDay parsable string](### TimeOfDay)
```
This syntax seem to work better:
```
[TimeOfDay parsable string](#TimeOfDay)
```

**Pull request merged**
