### PR TITLE
refactor: rename the openhab item to oh_item in the wrappers

### PR DESCRIPTION
**Pull request by jimtng**
An alternative to #242. If you know of a better way, feel free to discard this PR

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Hey @jimtng  - I am afraid I am not following.  This is instead of #242?

**Comment by boc-tothefuture** [comment]
Can you rebase off master? I fixed the testing.

**Comment by jimtng** [comment]
> Hey @jimtng - I am afraid I am not following. This is instead of #242?

Correct, this is an alternative solution to having oh_item instead of #242 
I think I prefer #242 but each has its pros and cons. WDYT?

#242 also includes the fix for store_states but I can make a separate PR for that if necessary.

**Comment by boc-tothefuture** [comment]
It certainly seems much easier than 243, so I would go with this one unless you have a reason to prefer the other?

**Comment by jimtng** [comment]
> It certainly seems much easier than 243, so I would go with this one unless you have a reason to prefer the other?

I'm a bit confused. This one *is* 243, where I manually renamed all the underlying item to oh_item. 

The other one, #242, left the underlying item variable name as is, and just creates a method called oh_item that returns the underlying item given via def_item_delegator

**Comment by boc-tothefuture** [comment]
@jimtng sorry - my bad.. I meant #242 seems easier and better.  If the do the same things.. lets close this one and add tests to the other so we can merge.

**Pull request closed without merging**
