### PR TITLE
fix some typos in the docs

### PR DESCRIPTION
**Pull request by ccutrer**

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
Hey @ccutrer  Thanks for the contribution!  
This repo follows the conventional commits process:   https://www.conventionalcommits.org/en/v1.0.0/

Can you squash/rebase your changes with a single commit message? 

In this case your message would be:

`fix(docs): removed duplicate "compare" in multiple places`

That should enable the commit-lint check to pass. 

Thanks and let me know if you need any help rebasing/squashing.

**Comment by ccutrer** [comment]
commit message updated. and yeah, I've kept things as a single commit. I notice rubocop failed. this is because you didn't commit the lockfile. are you okay with me pushing up a separate PR that commits the lockfile, and addresses any new rubocop warnings?

**Comment by boc-tothefuture** [comment]
> commit message updated. and yeah, I've kept things as a single commit. I notice rubocop failed. this is because you didn't commit the lockfile. are you okay with me pushing up a separate PR that commits the lockfile, and addresses any new rubocop warnings?

Sorry, I didn't see this before I pushed the fix for the rubocop issues.  I noticed that as well.  Once that is merged you can rebase off of it.  

We weren't pushing the lockfile, we went back and forth on it and ended up not pushing it.  Let me go see if I can find the discussion on why.

**Comment by ccutrer** [comment]
https://www.dragonastronauts.com/2019/08/14/should-you-add-gemfile-lock-to-git/ is a good summary. I too was originally in the "no lockfile in gems" camp. But as development workflows have progressed over the years, _especially_ with rubocop, and with Bundler recording which version of bundler was used in the lockfile (and having RubyGems hooks to automatically select the correct version of bundler at runtime), I've come round to it. Other more modern practices I've come round to is binstubs (i.e. bin/rubocop, bin/rake) to ensure you're running the correct versions, without having to type out a full `bundle exec` (or have an alias for it, and combined with a .envrc and [direnv](https://direnv.net) to automatically add the bin dir to your path).

**Comment by boc-tothefuture** [comment]
I am fine with moving to putting the Gemfile.lock based on that article or certainly giving it a shot.   Can you open a separate PR for that once I merge the rubocop fixes to main?

**Comment by ccutrer** [comment]
Will do!

**Comment by ccutrer** [comment]
Gemfile lock pushed as a separate PR. But I'm confused... it looks like you're using a merge workflow (forcing a merge commit, even if the PR is a fast-forward of main). If so, why are you requiring a rebase for something that clearly doesn't conflict (either technically, or semantically)?

**Comment by ccutrer** [comment]
Oh duh, so that this passes tests

**Comment by ccutrer** [comment]
okay, rebased

**Pull request merged**
