### PR TITLE
feat: allow TimeOfDay comparison against string

### PR DESCRIPTION
**Pull request by jimtng**
Allows the following code

```ruby
if TimeOfDay.now < '15:00'
#do something
end
```

Update README.md

### CODE REVIEW

**Comment by boc-tothefuture** [comment]
👍

**Comment by boc-tothefuture** [comment]
Should we add something in the README?

**Comment by jimtng** [comment]
> Should we add something in the README?

I'll work on this. I also have some other ideas for TimeOfDay which may belong in a separate PR.

**Comment by jimtng** [comment]
Writing docs isn't my strongest suit. I'd welcome any suggestions / changes for README

**Comment by boc-tothefuture** [comment]
I pushed a test case, if you think the test case makes sense I am ready to merge.

**Comment by jimtng** [comment]
> I pushed a test case, if you think the test case makes sense I am ready to merge.

cucumber tests still an alien to me. However, it does look reasonable, and I tried it and it passed.

**Pull request merged**
