### PR TITLE
fix(logging): logger doesn't show the rule name

### LINKED ISSUE #84: logger doesn't show the rule name
Currently when logging from inside a rule, the log shows:

```ruby
rule 'rule1 ' do
  on_start
  run do
    logger.info("Test logging from rule #{name}")
  end
end
```

```
15:12:34.417 [INFO ] [.OpenHAB::Core::DSL::Rule::RuleConfig] - Test logging from rule rule1
```

What it should say is:
```
15:12:34.417 [INFO ] [jsr223.jruby.rule1] - Test logging from rule rule1
```

### PR DESCRIPTION
**Pull request by jimtng**
Resolve #84

### CODE REVIEW

**Comment by jimtng** [comment]
This PR doesn't include a fix for the test. The test produced a false positive. The test passed even though logger didn't show the rule name in the log. It passed because a previous trace log had the rule name. I wrote the details in https://github.com/boc-tothefuture/openhab-jruby/issues/84#issuecomment-858137736

**Comment by jimtng** [comment]
It seems that #226 caused the regression on #84, because now this PR brings back the error that #226 fixed.

**Comment by boc-tothefuture** [comment]
I think we will have to manually set the rule name when we create the logger.

**Comment by jimtng** [comment]
> I think we will have to manually set the rule name when we create the logger.

not ideal. I wonder if we could just make "between" prop and call the caller's context `between` when it's running inside the rule execution (run, triggered)?

**Comment by boc-tothefuture** [comment]
Hey @jimtng - Just saw this has been lurking out here.. 

By manually above I just meant in the code here, not by the end user.

**Comment by jimtng** [comment]
> By manually above I just meant in the code here, not by the end user.

Thanks for the clarification. This would be great, but I'm a bit lost. When the run context is set to the caller, the `name` property is not visible to the logger method.

**Comment by boc-tothefuture** [comment]
I think (haven't tested), that we would have to make the following changes:

Right now we do 
`include OpenHAB::Log`

We would have to remove that and then in initialize do a
`@logger = Logger.new(config.name)`

then change the calls in the class to be @logger instead of logger.

**Comment by jimtng** [comment]
> I think (haven't tested), that we would have to make the following changes:
> 
> Right now we do
> `include OpenHAB::Log`
> 
> We would have to remove that and then in initialize do a
> `@logger = Logger.new(config.name)`
> 
> then change the calls in the class to be @logger instead of logger.

I tried this on automation_rule.rb but maybe I did something wrong. It didn't work, the behaviour remain unchanged. config.caller context is `main` so the @logger defined inside AutomationRule isn't being used by the code executed in the run block.

**Comment by boc-tothefuture** [comment]
Maybe I am misunderstanding the problem.  

Can you provide an example of where you are logging that we are seeing the issue?

**Comment by jimtng** [comment]
> Maybe I am misunderstanding the problem.
> 
> Can you provide an example of where you are logging that we are seeing the issue?

I updated https://github.com/boc-tothefuture/openhab-jruby/issues/84 with further details.

**Comment by pacive** [comment]
> I think (haven't tested), that we would have to make the following changes:
> 
> Right now we do
> `include OpenHAB::Log`
> 
> We would have to remove that and then in initialize do a
> `@logger = Logger.new(config.name)`
> 
> then change the calls in the class to be @logger instead of logger.

How would this affect users' logging in their rules? Would one have to use `@logger.info("Message")` instead of just `logger.info`?

**Comment by jimtng** [comment]
Since I'm not sure how to solve the scope issue, should I close this PR? The problem remains, however.

**Pull request closed without merging**
