### PR TITLE
feat(script_callbacks): make script_loaded/unloaded accessible

### PR DESCRIPTION
**Pull request by ccutrer**

### CODE REVIEW

**Comment by ccutrer** [comment]
I need to document it, but I want to see if the tests pass in GitHub. They don't pass locally, but they also don't pass locally without my commit.

**Comment by ccutrer** [comment]
@boc-tothefuture : can you try the failing test (`cucumber features/guards.feature:241`)? It has failed twice on GitHub now, but passes for me locally.

**Comment by boc-tothefuture** [comment]
Sure.  Will take a look.  We probably need a test (doing it from a rule) so we prevent any future regression.

**Comment by boc-tothefuture** [comment]
@ccutrer it worked when I reran the test.

**Comment by ccutrer** [comment]
Cool. Is this ready to merge then, or do you want to wait until https://github.com/boc-tothefuture/openhab-jruby/issues/366 is resolved?

**Comment by boc-tothefuture** [comment]
I think it can be merged - can you add a test for it to prevent regressions?

It isn't super useful until #366 is fixed, but it doesn't hurt it to be out there.

**Comment by ccutrer** [comment]
I didn't add any specific tests because of how I changed to timer canceling to use this, the existing tests already exercise it. That and unloaded tests don't work for me locally, so it's really hard...

I could definitely add one for loaded though.

**Comment by jimtng** [comment]
> I could definitely add one for loaded though.

+1 for this. As you've suggested, I could use this for my motion trigger dsl.

**Comment by boc-tothefuture** [comment]
You want to add the loaded test and fix the merge conflict and I can merge this?

**Comment by jimtng** [comment]
I wrote the tests and adjust openhab.rb, but I'm not sure how to combine it into the PR https://github.com/ccutrer/openhab-jruby/commit/e316fefae8cd44b94584484942ab67880b1f8b40

**Comment by jimtng** [comment]
Sorry this merge is wrong: https://github.com/boc-tothefuture/openhab-jruby/pull/368/commits/a7ce7996a39464a13ddd248f2d4566a066d7d231

My commit https://github.com/jimtng/openhab-jruby/commit/e316fefae8cd44b94584484942ab67880b1f8b40 has the correct version of openhab.rb.

**Comment by jimtng** [comment]
Sorry I kept forgetting to uncomment the tests. I usually comment out all the other tests in the file to focus on one particular test. I think it's good now.

**Comment by boc-tothefuture** [comment]
> Sorry I kept forgetting to uncomment the tests. I usually comment out all the other tests in the file to focus on one particular test. I think it's good now.

Just FYI - you can run specific tests and even specific scenario examples within having to comment and uncomment things.

```
bin/cucumber features/feature:<line_number_of_scenario>
```

**Comment by boc-tothefuture** [comment]
This PR keeps failing on the same test.  At first I thought we just had something unstable but it does appear this PR is potentially introducing a defect.  Other PRs have been passing.

**Comment by jimtng** [comment]
It's failing on YARD coverage with weird error messages.

**Comment by jimtng** [comment]
Those mixin "errors" were there in other PRs too. The YARD coverage was failing because of an undocumented module and 2 undocumented methods. I've added comments above the corresponding items and it now passed the YARD test

**Comment by boc-tothefuture** [comment]
Before that I ran it twice and it failed on the changed_duratiom test.  But it does appear to be passing now.

**Pull request merged**
